import { defineConfig } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';

export default defineConfig([
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'next-env.d.ts',
      // Generated by drizzle-kit - never lint or edit by hand (see AGENTS.md).
      'src/db/migrations/**',
    ],
  },
  ...nextVitals,
  ...nextTypeScript,
]);
